src/Entity/Item.php
<?php

namespace App\Entity;

use App\Repository\ItemRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ItemRepository::class)
 */
class Item
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $year;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="text")
     */
    private $preface;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $video;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity=ItemCategory::class, inversedBy="items")
     */
    private $item_categories;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="items")
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity=CommentItem::class, mappedBy="items")
     */
    private $commentItems;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="item")
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
        $this->users = new ArrayCollection();
        $this->commentItems = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getPreface(): ?string
    {
        return $this->preface;
    }

    public function setPreface(string $preface): self
    {
        $this->preface = $preface;

        return $this;
    }

    public function getVideo(): ?string
    {
        return $this->video;
    }

    public function setVideo(?string $video): self
    {
        $this->video = $video;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getItemCategories(): ?ItemCategory
    {
        return $this->item_categories;
    }

    public function setItemCategories(?ItemCategory $item_categories): self
    {
        $this->item_categories = $item_categories;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addItem($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeItem($this);
        }

        return $this;
    }

    /**
     * @return Collection|CommentItem[]
     */
    public function getCommentItems(): Collection
    {
        return $this->commentItems;
    }

    public function addCommentItem(CommentItem $commentItem): self
    {
        if (!$this->commentItems->contains($commentItem)) {
            $this->commentItems[] = $commentItem;
            $commentItem->setItems($this);
        }

        return $this;
    }

    public function removeCommentItem(CommentItem $commentItem): self
    {
        if ($this->commentItems->removeElement($commentItem)) {
            // set the owning side to null (unless already changed)
            if ($commentItem->getItems() === $this) {
                $commentItem->setItems(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Controller/Back/CommentController.php
<?php

namespace App\Controller\Back;

use App\Entity\CommentItem;
use App\Entity\CommentMedia;
use App\Form\CommentItem1Type;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\CommentItemRepository;
use App\Repository\CommentMediaRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/admin/comment", name="admin_comment_", requirements={"id"="\d+"})
 */
class CommentController extends AbstractController
{
    /**
     * @Route("/media", name="media_index", methods={"GET"})
     */
    public function indexCommentMedia(CommentMediaRepository $commentMediaRepository): Response
    {
        return $this->render('back/comment/media/index.html.twig', [
            'commentMedias' => $commentMediaRepository->findBy([], ['id' => 'DESC']),
        ]);
    }

    /**
     * @Route("/item", name="item_index", methods={"GET"})
     */
    public function indexCommentItem(CommentItemRepository $commentItemRepository): Response
    {
        return $this->render('back/comment/item/index.html.twig', [
            'commentItems' => $commentItemRepository->findBy([], ['id' => 'DESC']),
        ]);
    }

    /**
     * @Route("/media/{id}", name="media_show", methods={"GET"})
     */
    public function showCommentMedia(CommentMedia $commentMedia): Response
    {
        return $this->render('back/comment/media/show.html.twig', [
            'commentMedia' => $commentMedia,
        ]);
    }

    /**
     * @Route("/item/{id}", name="item_show", methods={"GET"})
     */
    public function showCommentItem(CommentItem $commentItem): Response
    {
        return $this->render('back/comment/item/show.html.twig', [
            'commentItem' => $commentItem,
        ]);
    }

    /**
     * @Route("/media/{id}", name="media_delete", methods={"POST"})
     */
    public function deleteCommentMedia(Request $request, CommentMedia $commentMedia, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commentMedia->getId(), $request->request->get('_token'))) {
            $entityManager->remove($commentMedia);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_comment_media_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/item/{id}", name="item_delete", methods={"POST"})
     */
    public function deleteCommentItem(Request $request, CommentItem $commentItem, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commentItem->getId(), $request->request->get('_token'))) {
            $entityManager->remove($commentItem);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_comment_item_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Back/HomeController.php
<?php

namespace App\Controller\Back;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/admin", name="admin")
     */
    public function index(): Response
    {
        return $this->render('back/home/index.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }
}

src/Controller/Back/ItemCategoryController.php
<?php

namespace App\Controller\Back;

use App\Entity\ItemCategory;
use App\Form\ItemCategoryType;
use App\Repository\ItemCategoryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/item/category", name="admin_item_category_", requirements={"id"="\d+"})
 */
class ItemCategoryController extends AbstractController
{
    /**
     * @Route("/", name="index", methods={"GET"})
     */
    public function index(ItemCategoryRepository $itemCategoryRepository): Response
    {
        return $this->render('back/item_category/index.html.twig', [
            'item_categories' => $itemCategoryRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $itemCategory = new ItemCategory();
        $form = $this->createForm(ItemCategoryType::class, $itemCategory);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($itemCategory);
            $entityManager->flush();

            return $this->redirectToRoute('admin_item_category_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/item_category/new.html.twig', [
            'item_category' => $itemCategory,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="show", methods={"GET"})
     */
    public function show(ItemCategory $itemCategory): Response
    {
        return $this->render('back/item_category/show.html.twig', [
            'item_category' => $itemCategory,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, ItemCategory $itemCategory, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ItemCategoryType::class, $itemCategory);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('admin_item_category_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/item_category/edit.html.twig', [
            'item_category' => $itemCategory,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="delete", methods={"POST"})
     */
    public function delete(Request $request, ItemCategory $itemCategory, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$itemCategory->getId(), $request->request->get('_token'))) {
            $entityManager->remove($itemCategory);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_item_category_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Back/ItemController.php
<?php

namespace App\Controller\Back;

use App\Entity\Item;
use App\Form\ItemType;
use App\Service\Slugger;
use App\Service\ImageUploader;
use App\Repository\ItemRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/admin/item", name="admin_item_", requirements={"id"="\d+"})
 */
class ItemController extends AbstractController
{

    /**
     * filtering of categories using findBy with
     * the id of the corresponding media_categories
     * @Route("/liste/{id}", name="index", methods={"GET"})
     */
    public function index(ItemRepository $itemRepository, $id): Response
    {
        return $this->render('back/item/index.html.twig', [
            'items' => $itemRepository->findBy(['item_categories' => $id], []),
        ]);
    }

    /**
     * @Route("/new", name="new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager, Slugger $slugger,  ImageUploader $imageUploader): Response
    {
        $item = new Item();
        $form = $this->createForm(ItemType::class, $item);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $image = $form->get('image')->getData();
            if ($image != null) {
                // Use of the ImageUploader service allowing the user to upload a profile picture
                $imageUploader->uploadItemImage($form);
            }
            // Processing Slug
            $slugger->slugifyItem($item);

            $entityManager->persist($item);
            $entityManager->flush();

            return $this->redirectToRoute('admin', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/item/new.html.twig', [
            'item' => $item,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="show", methods={"GET"})
     */
    public function show(Item $item): Response
    {
        return $this->render('back/item/show.html.twig', [
            'item' => $item,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Item $item, EntityManagerInterface $manager, Slugger $slugger,  ImageUploader $imageUploader): Response
    {
        $form = $this->createForm(ItemType::class, $item);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $image = $form->get('image')->getData();
            if ($image != null) {
                // Use of the ImageUploader service allowing the user to upload a profile picture
                $imageUploader->uploadItemImage($form);
            }
            // Processing Slug
            $slugger->slugifyItem($item);

            $manager->flush();

            return $this->redirectToRoute('admin', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/item/edit.html.twig', [
            'item' => $item,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="delete", methods={"POST"})
     */
    public function delete(Request $request, Item $item, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $item->getId(), $request->request->get('_token'))) {
            $entityManager->remove($item);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin', [], Response::HTTP_SEE_OTHER);
    }
}

templates/back/item/_delete_form.html.twig
<form method="post" action="{{ path('admin_item_delete', {'id': item.id}) }}" onsubmit="return confirm('Etes-vous certain de vouloir supprimer cet item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ item.id) }}">
	<button class="btn btn-purple my-2 col-4">Supprimer</button>
</form>

templates/back/item/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form,{'attr': {'class': 'form-purple'} }) }}
    <p class="form-purple">( * Champs obligatoires )</p>
    <button class="btn btn-purple my-2 col-4">{{ button_label|default('Créer') }}</button>
{{ form_end(form) }}

templates/back/item/edit.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}
Éditer cet Item
{% endblock %}
{% block body %}
	<h1 class="text-center my-4" id="detail-title">Éditer cet Item</h1>

	{{ include('back/item/_form.html.twig', {'button_label': 'Modifier'}) }}

	{{ include('back/item/_delete_form.html.twig') }}

	<a href="{{ path('admin') }}" class="btn btn-purple my-2 mx-2 col-4">Retour au backoffice</a>
{% endblock %}

templates/back/item/index.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}
Items
{% endblock %}
{% block body %}

	<div class="col-12 text-center my-4">
		<h1 id="detail-title">Liste des Entrées</h1>
	</div>
	<div class="text-end">
	<a href="{{ path('admin_item_new') }}"class="btn btn-purple my-2 col-3">Ajouter une Entrée</a>
	</div>
	<table class="table table-hover card-purple">
		<thead>
			<tr>
				<th scope="col">ID</th>
				<th scope="col">Titre</th>
				<th scope="col">Création</th>
				<th scope="col">Dernière modification</th>
				<th scope="col"></th>
			</tr>
		</thead>
		<tbody>
			{% for item in items %}
				<tr class="table-{{ cycle(['primary', 'secondary'], loop.index) }} card-purple">
					<th scope="row">{{ item.id }}</th>
					<td>{{ item.name }}</td>
					<td>{{ item.createdAt|date('d/m/Y') }}</td>
					<td>{{ item.updatedAt ? item.updatedAt|date('d/m/Y') }}</td>
					<td class="text-end">
              			<a href="{{ path('admin_item_show', {id: item.id}) }}" class="fs-4 btn-back-tool"
                			><i class="fa fa-eye" aria-hidden="true"></i></a>
              			<a href="{{ path('admin_item_edit', {id: item.id}) }}" class="fs-4 btn-back-tool"
                			><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
              			<form action="{{ path('admin_item_delete', {id: item.id}) }}" class="d-inline" method="post">
                			<button class="btn btn-back-tool p-0 mb-2 fs-4"><i class="fa fa-trash" aria-hidden="true"></i></button>
                			<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ item.id) }}">
              			</form>
            		</td>
				</tr>
		{% else %}
			<tr>
				<td colspan="16">Aucune donnée trouvée</td>
			</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

templates/back/item/new.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}
Ajouter un Item
{% endblock %}
{% block body %}
	<h1 class="text-center my-4" id="detail-title">Créer un Nouvel Item</h1>

	{{ include('back/item/_form.html.twig') }}

	<a href="{{ path('admin') }}" class="btn btn-purple mx-2 my-2 col-4">Retour au BackOffice</a>
{% endblock %}

templates/back/item/show.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}
{{ item.name }}
{% endblock %}
{% block body %}
	<h1 class="text-center my-4" id="detail-title">{{ item.name }}</h1>

	<table class="table my-2 card-purple">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ item.id }}</td>
			</tr>
			<tr>
				<th>Titre</th>
				<td>{{ item.name }}</td>
			</tr>
			<tr>
				<th>Catégorie</th>
				<td>{{ item.itemCategories.name }}</td>
			</tr>
			<tr>
				<th>Année</th>
				<td>{{ item.year }}</td>
			</tr>
			<th>Image en local</th>
				{% if  file_service.exist(asset('items/' ~ item.image)) == true %}
					<td><img src="{{ asset('assets/images/items/' ~ item.image) }}" class="max-image-size-back"/></td>
				{% else %}
					<td>Pas d'image en local	╮(︶︿︶)╭</td>
				{% endif %}
			<tr>
				<th>Préface</th>
				<td>{{ item.preface }}</td>
			</tr>
			<tr>
				<th>Publicité</th>
				{% if item.video != null %}
					<td class="embed-responsive embed-responsive-16by9 text-center m-4">
						<iframe width="640" height="360" src={{ item.video }} frameborder="0" allow="autoplay; encrypted-media" class="rounded" allowfullscreen></iframe>
					</td>
				{% else %}
					<td>Pas de Publicité en BDD ╮(︶︿︶)╭</td>
				{% endif %}
			</tr>
			<tr>
				<th>Créé le</th>
				<td>{{ item.createdAt ? item.createdAt|date('d/m/Y') : '' }}</td>
			</tr>
			<tr>
				<th>Mis à jour le</th>
				<td>{{ item.updatedAt ? item.updatedAt|date('d/m/Y') : '' }}</td>
			</tr>
		</tbody>

	</table>

	<a href="{{ path('admin_item_edit', {id:item.id}) }}" class="btn btn-purple mx-2 my-2 col-4">Modifier</a>

	{{ include('back/item/_delete_form.html.twig') }}

	<a href="{{ path('admin') }}" class="btn btn-purple mx-2 my-2 col-4">Retour au BackOffice</a>

{% endblock %}