src/Entity/Media.php
<?php

namespace App\Entity;

use App\Repository\MediaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MediaRepository::class)
 */
class Media
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="smallint")
     */
    private $year;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $duration;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $nb_season;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $nb_episode;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $duration_episode;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $preface;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $synopsis;

    /**
     * @ORM\Column(type="text")
     */
    private $summary;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $anecdote;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $trailer;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToMany(targetEntity=Person::class, inversedBy="medias")
     */
    private $persons;

    /**
     * @ORM\ManyToMany(targetEntity=Type::class, inversedBy="medias")
     */
    private $types;

    /**
     * @ORM\ManyToOne(targetEntity=MediaCategory::class, inversedBy="medias")
     */
    private $media_categories;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="medias")
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity=CommentMedia::class, mappedBy="medias")
     */
    private $comment_medias;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="media")
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $original_title;

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
        $this->persons = new ArrayCollection();
        $this->types = new ArrayCollection();
        $this->users = new ArrayCollection();
        $this->comment_medias = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(?int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getNbSeason(): ?int
    {
        return $this->nb_season;
    }

    public function setNbSeason(?int $nb_season): self
    {
        $this->nb_season = $nb_season;

        return $this;
    }

    public function getNbEpisode(): ?int
    {
        return $this->nb_episode;
    }

    public function setNbEpisode(?int $nb_episode): self
    {
        $this->nb_episode = $nb_episode;

        return $this;
    }

    public function getDurationEpisode(): ?int
    {
        return $this->duration_episode;
    }

    public function setDurationEpisode(?int $duration_episode): self
    {
        $this->duration_episode = $duration_episode;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getPreface(): ?string
    {
        return $this->preface;
    }

    public function setPreface(?string $preface): self
    {
        $this->preface = $preface;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(?string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getAnecdote(): ?string
    {
        return $this->anecdote;
    }

    public function setAnecdote(?string $anecdote): self
    {
        $this->anecdote = $anecdote;

        return $this;
    }

    public function getTrailer(): ?string
    {
        return $this->trailer;
    }

    public function setTrailer(?string $trailer): self
    {
        $this->trailer = $trailer;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Person[]
     */
    public function getPersons(): Collection
    {
        return $this->persons;
    }

    public function addPerson(Person $person): self
    {
        if (!$this->persons->contains($person)) {
            $this->persons[] = $person;
        }

        return $this;
    }

    public function removePerson(Person $person): self
    {
        $this->persons->removeElement($person);

        return $this;
    }

    /**
     * @return Collection|Type[]
     */
    public function getTypes(): Collection
    {
        return $this->types;
    }

    public function addType(Type $type): self
    {
        if (!$this->types->contains($type)) {
            $this->types[] = $type;
        }

        return $this;
    }

    public function removeType(Type $type): self
    {
        $this->types->removeElement($type);

        return $this;
    }

    public function getMediaCategories(): ?MediaCategory
    {
        return $this->media_categories;
    }

    public function setMediaCategories(?MediaCategory $media_categories): self
    {
        $this->media_categories = $media_categories;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addMedia($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeMedia($this);
        }

        return $this;
    }

    /**
     * @return Collection|CommentMedia[]
     */
    public function getCommentMedias(): Collection
    {
        return $this->comment_medias;
    }

    public function addCommentMedia(CommentMedia $commentMedia): self
    {
        if (!$this->comment_medias->contains($commentMedia)) {
            $this->comment_medias[] = $commentMedia;
            $commentMedia->setMedias($this);
        }

        return $this;
    }

    public function removeCommentMedia(CommentMedia $commentMedia): self
    {
        if ($this->comment_medias->removeElement($commentMedia)) {
            // set the owning side to null (unless already changed)
            if ($commentMedia->getMedias() === $this) {
                $commentMedia->setMedias(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getOriginalTitle(): ?string
    {
        return $this->original_title;
    }

    public function setOriginalTitle(?string $original_title): self
    {
        $this->original_title = $original_title;

        return $this;
    }
}

src/Controller/Back/MediaController.php
<?php

namespace App\Controller\Back;

use App\Entity\Media;
use App\Form\MediaType;
use App\Repository\MediaRepository;
use App\Service\Slugger;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/media", name="admin_media_", requirements={"id"="\d+"})
 */
class MediaController extends AbstractController
{

    /**
     * filtering of categories (movie, series, cartoon, etc.) using findBy with
     * the id of the corresponding media_categories
     * @Route("/liste/{id}", name="index", methods={"GET"})
     */
    public function index(MediaRepository $mediaRepository, $id): Response
    {
        return $this->render('back/media/index.html.twig', [
            'medias' => $mediaRepository->findBy(['media_categories' => $id], []),
        ]);
    }

    /**
     * @Route("/new", name="new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager, Slugger $slugger): Response
    {
        $media = new Media();
        $form = $this->createForm(MediaType::class, $media);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Processing Slug
            $slugger->slugifyMedia($media);

            $entityManager->persist($media);
            $entityManager->flush();

            return $this->redirectToRoute('admin', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/media/new.html.twig', [
            'media' => $media,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="show", methods={"GET"})
     */
    public function show(Media $media): Response
    {
        return $this->render('back/media/show.html.twig', [
            'media' => $media,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Media $media, EntityManagerInterface $entityManager, Slugger $slugger): Response
    {
        $form = $this->createForm(MediaType::class, $media);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Processing Slug
            $slugger->slugifyMedia($media);

            $entityManager->flush();

            return $this->redirectToRoute('admin', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/media/edit.html.twig', [
            'media' => $media,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="delete", methods={"POST"})
     */
    public function delete(Request $request, Media $media, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $media->getId(), $request->request->get('_token'))) {
            $entityManager->remove($media);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Front/HomeController.php
<?php

namespace App\Controller\Front;

use App\Repository\ItemRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(ItemRepository $itemRepository, Request $request): Response
    {   
        $items = $itemRepository->findBy([], ['id' => 'DESC'], 4);
        $candies = $itemRepository->findBy(['item_categories' => 1], ['id' => 'DESC'], 3);
        $objects = $itemRepository->findBy(['item_categories' => 2], ['id' => 'DESC'], 3);
        $toys = $itemRepository->findBy(['item_categories' => 3], ['id' => 'DESC'], 3);
        return $this->render('front/home/index.html.twig', [
            'items' => $items,
            'candies' => $candies,
            'objects' => $objects,
            'toys' => $toys,
        ]);
    }
}

src/Controller/Front/PageController.php
<?php

namespace App\Controller\Front;

use App\Form\ContactType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class PageController extends AbstractController
{
    /**
     * To go to the contact form
     * 
     * @Route("/contact", name="contact")
     */
    public function contact(Request $request)
    {
        // we call creatForm method of the Form class to use the FormType
        $form = $this->createForm(ContactType::class);

        // we ask to form to check inputs in POST to validate the form
        $form->handleRequest($request);

        // we test if the form sended is valid
        if ($form->isSubmitted() && $form->isValid()) {
            $form->getData();
        }

        return $this->render('front/page/contact.html.twig',  [
            'form' => $form->createView()
        ]);
    }

    /** 
     * To show legal mention of the website
     * 
     * @Route("/legalmention", name="legal_mention")
     * 
     * @return Response
     */
    public function legal()
    {
        return $this->render('front/page/legalmention.html.twig');
    }

    /** 
     * To show sitemap of the website
     * 
     * @Route("/sitemap", name="sitemap")
     * 
     * @return Response
     */
    public function sitemap()
    {
        return $this->render('front/page/sitemap.html.twig');
    }

    /**
     * To download charte in PDF
     * 
     * @Route("/charte/download", name="charte_download")
     *
     * @return Response
     */
    public function download()
    {
        return $this->file('assets/charte_download.pdf');
    }

}

src/Controller/Front/PersonController.php
<?php

namespace App\Controller\Front;

use App\Entity\Person;
use App\Form\PersonType;
use App\Repository\PersonRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/person", name="person_", requirements={"id"="\d+"})
 */
class PersonController extends AbstractController
{

    /**
     * @Route("/{id}", name="show", methods={"GET"})
     */
    public function show(Person $person, PersonRepository $personRepository): Response
    {
        return $this->render('front/person/show.html.twig', [
            'person' => $person,
        ]);
    }

    /**
     * @Route("/new", name="new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $person = new Person();
        $form = $this->createForm(PersonType::class, $person);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
           
            $entityManager->persist($person);
            $entityManager->flush();

            $this->addFlash('success', 'Nouvelle Personne Ajoutée !');

            return $this->redirectToRoute('home', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('front/person/new.html.twig', [
            'person' => $person,
            'form' => $form,
        ]);
    }

}

templates/front/media/_media_comments.html.twig
{# AJOUTER UN COMMENTAIRE #}
{% if is_granted('ROLE_USER') %}
	<div class="row d-flex justify-content-center">
		<div class="card bloc-detail col-10 gutter-0 id=ajout-commentaire pt-3">
		    <div class="bloc-contour-detail m-3 p-3">
			{{ form_start(commentForm) }}
			{{ form_widget(commentForm,{'attr': {'class': 'form-purple'} }) }}
			<button class="btn btn-purple my-2 col-4">{{ button_label|default('Envoyer') }}</button>
			{{ form_end(commentForm) }}
			</div>
		</div>
	</div>
	{% else %}
		<div class="row d-flex justify-content-center">
			<div class="ajout-comment col-4 gutter-0 id=ajout-commentaire p-3">
				<p class="text-center">Connectez-vous pour ajouter un commentaire</p>
				<a type="button" class="btn btn-login my-2 my-sm-0  d-none d-lg-block" href="{{ path('app_login') }}">S'enregistrer / Connexion</a>
			</div>
		{% endif %}

{# LISTE DES COMMENTAIRES #}
		<div class="row d-flex justify-content-center pt-3">

			<div class="comment-dark col-10 gutter-0">
				<h3 class="list-comment m-4">Liste des commentaires</h3>
				<hr>
				{% for commentMedias in media.commentMedias %}

            <!-- profil user -->
			{% if commentMedias.parent == null %}
				<h5 class="number-comment">Commentaire {{loop.index}}</h5>
                <div class="row d-flex justify-content-around">
                <div class="col-5 col-xxl-3 p-2">
              {% if commentMedias.users.nickname != null %}
                        {% if commentMedias.users.image != null %}
                        <img src="{{ asset('assets/images/utilisateurs/' ~ commentMedias.users.image) }}" class="card-img rounded-lg m-2" alt="..." style="width: 7rem; height: 7rem">
                      	{% else %}
                          <img src="{{ asset('../assets/images/utilisateurs/anonymous.jpg') }}" class="card-img rounded-lg m-2" alt="..." style="width: 7rem; height: 7rem">
                        {% endif %}
				     <p class="content-comment">Le 
				      {{commentMedias.createdAt|date("d/m/Y") }} 
				     </p>
                     <p class="pseudo-comment"> 
				     {{ commentMedias.users.nickname }}
				      </p>
              {% endif %}

                 </div>

							<!-- contenu comment -->
							<div class="bloc-detail border-purple col-6 col-xxl-8 m-2 mb-4 p-5 center">
								<p class="content-comment">{{commentMedias.content|raw}}</p>
								{% if commentMedias.image != null %}
									{# We get the path of the images folder from the .env and we store it in a variable #}
									{% set commentImage = app.request.server.get('COMMENT_IMAGES') %}
									<img src="{{ asset(commentImage ~ '/' ~ commentMedias.image) }}" class="card-img rounded" alt="..." style="width: 10rem; margin-bottom: 10px;">
								{% endif %}
							</div>
						</div>
						<hr>

					{% endif %}
				{% endfor %}
			</div>
		</div>
	</div>

templates/front/media/new.html.twig
{% extends "front/base.html.twig" %}

{% block title %}Ajouter un Média
{% endblock %}

{% block body %}

	<div class="container">
			<h1 class="text-center my-4" id="detail-title">Proposer un nouveau Média</h1>
		<div class="col-10 mx-auto my-2">
			{{ form_start(form) }}
			{{ form_widget(form,{'attr': {'class': 'form-purple'} }) }}
			<p class="form-purple">( * Champs obligatoires )</p>
			<button class="btn col-4 btn-purple">Ajouter</button>

			{{ form_end(form) }}
		</div>
	</div>

{% endblock %}

templates/front/media/show.html.twig
{% set currentRoute = app.request.get('_route') %}

{% extends 'front/base.html.twig' %}

{% block title %}
	{{ media.title }}
{% endblock %}

{% block body %}
	<div class="container-fluid" witdh="90%">
		<div
			class="row d-flex justify-content-around">

			<!--icon favori-->
			<div
				class="col-4 text-center my-4">
				<!-- checking if the user is connected with an user role -->
				{% if is_granted("ROLE_USER") %}
					<!-- we browse the favorites in the media user table -->
					{% for mediafavorites in media.users %}
						<!-- if the id of the favorite matches the id of the user -->
						{% if mediafavorites.id == app.user.id %}
							<a href="{{ path('media_remove_favorite', {id : media.id}) }}">
								<i class="bi bi-heart-fill"></i>
							</a>
						{% else %}
							<a href="{{ path('media_add_favorite', {id : media.id}) }}">
								<i class="bi bi-heart"></i>
							</a>
						</a>
					{% endif %}
				{% else %}
					<a href="{{ path('media_add_favorite', {id : media.id}) }}">
						<i class="bi bi-heart"></i>
					</a>
				</a>
			{% endfor %}
		{% else %}
			<a href="" onclick="return confirm('Connectez-vous pour ajouter ce contenu en favoris ;)')">
				<i class="bi bi-heart"></i>
			</a>
		{% endif %}
	</div>

	<!--title -->
	<div class="col-4 text-center my-4">
		<h1 id="detail-title">{{ media.title }}</h1>
	</div>

	<!--icons partage-->
	<div class="col-4 text-center my-4 d-flex">
		{# <i class="bi bi-twitter mx-1" style="font-size: 2rem;"></i>
		<i class="bi bi-facebook mx-1" style="font-size: 2rem;"></i>
		<i class="bi bi-share-fill mx-1" style="font-size: 2rem;"></i> #}
	</div>
</div></div><!-- detail de l'annonce --><div
class=" row m-5 d-flex justify-content-center pt-2">

<!-- bloc image -->
<div class="col-10 col-xxl-5">
	{% if media.image != null %}
		<img src="{{ media.image }}" class="img-media d-block user-select-none mx-auto" aria-label="Image" focusable="false" role="img"/>
	{% else %}
		{# use of the service set up in App\Service\FileService.php to check whether a file exists or not #}
		{% if  file_service.exist(asset('api/' ~ media.originalTitle ~ '.jpg')) == true %}
			<img src="{{ asset('assets/images/api/' ~ media.originalTitle ~ '.jpg') }}" class="img-media d-block user-select-none mx-auto  align-self-center" aria-label="Image" focusable="false" role="img"/>
		{% else %}
			<img src="{{ asset('assets/images/mire_error.jpg') }}" class="img-media d-block user-select-none mx-auto  align-self-center" width="90%" aria-label="Image" focusable="false" role="img"/>
		{% endif %}
	{% endif %}
</div>

<!-- bloc information -->
<div
	class="col-10 col-xxl-6 pt-5 pt-xxl-0">

	<!-- bloc tag genre et tag année ensemble-->
	<div class="card bloc-detail">
		<div
			class="card-body row d-flex justify-content-between m-3">

			<!-- tag du genre -->
			<div class="col-9 d-flex flex-row ruban">
				{% for type in media.types %}
					<form action="{{ path('type_filter') }}">
						<input name="filterType" type="hidden" value="{{ type.name }}">
						<button type="submit" class="type-media my-2 mx-1">{{ type.name }}</button>
					</form>
				{% endfor %}
			</div>


			<!-- Année -->
			<div class="col-3">
				<form action="{{ path('year_filter') }}" class="text-end">
					<input name="filterYear" type="hidden" value="{{ media.year }}">
					<button type="submit" class="year-tag m-2">{{ media.year }}</button>
				</form>
			</div>

			<!-- fin du bloc tag genre et tag année ensemble-->
		</div>


		<!-- durée ou nbre saisons / nbre episodes / durée d'un épisode -->
		<div
			class="row text-center text-light">
			<!-- Durée -->
			{% if media.duration != null %}
				<div class="col-3 mx-3">
					<p>Durée :
						{{ media.duration }}
						min</p>
				</div>
			{% endif %}
			<!-- Nombre de saison -->
			{% if media.nbSeason != null %}
				<div class="col-3 mx-3">
					<p>
						{{ media.nbSeason }}
						saison(s)
					</p>
				</div>
			{% endif %}
			<!-- Nombre d'épisodes -->
			{% if media.nbEpisode != null %}
				<div class="col-3 mx-3 text-center">
					<p>
						{{ media.nbEpisode }}
						épisodes
					</p>
				</div>
			{% endif %}
			<!-- Durée d'un épisode -->
			{% if media.durationEpisode != null %}
				<div class="col-3 mx-3 text-end">
					<p>
						{{ media.durationEpisode }}
						min par épisode
					</p>
				</div>
			{% endif %}
		</div>

		<!-- synopsis -->
		<div class="bloc-contour-detail mt-3 p-3 m-3">
			<h5 class="card-title-detail text-center text-light p-3">Synopsis</h5>
			<p class="card-resume-detail m-1">{{ media.synopsis }}</p>
		</div>


		<!-- Préface -->
		<div class="col-10 m-auto">
			{% if media.preface != null %}
				<p class="card-preface-media">{{ media.preface }}</p>
			{% endif %}
		</div>

		<!-- Anecdote -->
		{% if media.anecdote != null %}
			<div class="bloc-contour-detail mt-3 p-3 m-3">
				<h5 class="card-title-detail text-center text-light p-3">Anecdote</h5>
				<p class="card-resume-detail m-1">{{ media.anecdote }}</p>
			</div>
		{% endif %}


	</div>

	<!-- FIN DU BLOC INFORMATIONS -->
</div>

<!-- Video -->
{% if media.trailer != null %}
	<div class="embed-responsive embed-responsive-16by9 text-center m-4">
		<iframe width="640" height="360" src={{ media.trailer }} frameborder="0" allow="autoplay; encrypted-media" class="rounded" allowfullscreen></iframe>
	</div>
{% else %}
	<h3 class="card-title-detail text-center text-light m-2">Aucun trailer disponible pour
		{{ media.title }}
		désolé,<br> un petit générique Jean Mineur pour nous faire pardonner.</h3>
	<div class="embed-responsive embed-responsive-16by9 text-center m-4">
		<iframe width="640" height="360" src="https://www.youtube.com/embed/qBpA-BYxjZ8" frameborder="0" allow="autoplay; encrypted-media" class="rounded" allowfullscreen></iframe>
	</div>
{% endif %}

<!-- menu acteurs/réalisateurs/résumé -->
{% include "front/media/_media_details_menu.html.twig" %}

<!-- commentaires -->
{% include "front/media/_media_comments.html.twig" %}{% endblock %}